import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useState } from "react";
import Image from "next/image"
import Pagination from "../components/Pagination";

export default function Home({ posts }) {

  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 5;

  const onPageChange = (page) => {
    setCurrentPage(page);
  };

  const paginate = (items, pageNumber, pageSize) => {
    const startIndex = (pageNumber - 1) * pageSize;
    return items.slice(startIndex, startIndex + pageSize); // 0, 9
  };

  const paginatedPosts = paginate(posts, currentPage, pageSize);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.center}>Front-end technology blog </h1>
      <main className={styles.main}>

        <div className={styles.grid}>
          {paginatedPosts.map((post) => (

            <div className={styles.card} key={post.id}>
              <Link href={`/post/${encodeURIComponent(post.slug)}`} >
                <Image src={post.image} alt="Avatar" width="250" height="160" />

                <h3 style={{ marginTop: '10px' }}>{post.title}</h3>
                {/* <p className={styles.text}>{post.content}</p> */}

              </Link>
            </div>
          ))}

        </div>

        <div >
          <Pagination
            items={posts.length} 
            currentPage={currentPage}
            pageSize={pageSize}
            onPageChange={onPageChange}
          />

        </div>
      </main>
    </>
  )
}
export async function getServerSideProps() {
  const req = await fetch(`http://localhost:8080/`);
  const data = await req.json();

  return {
    props: { posts: data },
  }
}

