import Head from 'next/head'
import About from './posts'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Image from "next/image"
const inter = Inter({ subsets: ['latin'] })



//todo Page to fetch all data and display in card format (title, image, little bit content)

//todo press on card, creates link /blog-title, send to it, opens /posts/[pid].js file/page 


export default function Home({ posts }) {



  const router = useRouter()
  // const { id } = router.query

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.center}>Front-end technology blog </h2>
      <main className={styles.main}>

        <div className={styles.grid}>
          {posts.map((post) => (

            <div key={post.id}>
              <Link href={`/post/${encodeURIComponent(post.title)}`} className={styles.card}>
                <Image src={post.image} alt="Avatar" width="250" height="180" />
                <h4><b>{post.title}</b></h4>
                <p className={styles.text}>{post.content}</p>

              </Link>
            </div>
          ))}

        </div>

      </main>
    </>
  )
}
export async function getServerSideProps() {


  const req = await fetch(`http://localhost:8080/`);
  const data = await req.json();
  // console.log(data);
  return {
    props: { posts: data },
  }
}
