import Head from 'next/head'
import About from './posts'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Heyy</h2>

        <ul>
          <li>
            <Link href="/post/abc">A</Link>
          </li>
          <li>
            <Link href="/post/abc?foo=bar">B</Link>
          </li>
          <li>
            <Link href="/post/abc/a-comment">
              C
            </Link>
          </li>
        </ul>

      </main>
    </>
  )
}
