package main

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/mattn/go-sqlite3"
)

func database() {
	os.Remove("./database/database.db")

	log.Println("Creating sqlite-database.db...")

	file, err := os.Create("./database/database.db")
	if err != nil {
		log.Fatal(err.Error())
	}
	file.Close()
	log.Println("database.db created")

	dbConn, err := sql.Open("sqlite3", "./database/database.db")
	if err != nil {
		log.Fatal(err.Error())
		return
	}
	createPost(dbConn)

	defer dbConn.Close() // Defer Closing the database
}

// todo add image path to database
func createPost(dbConn *sql.DB) {
	statement, _ := dbConn.Prepare(`
	CREATE TABLE  post  (
		id  INTEGER not null PRIMARY KEY AUTOINCREMENT,
		username varchar(255) not null,
		title varchar(255) not null,
		content  text not null,
		image varchar(255) not null,
		created  datetime not null DEFAULT CURRENT_TIMESTAMP
	 )
		`)
	statement.Exec()
	stmt, err := dbConn.Prepare(`INSERT INTO post(id, username, title, content, image, created) VALUES(?, ?, ?, ?, ?, ?)`)
	if err != nil {
		log.Fatal(err.Error())
		return
	}
	stmt.Exec("1", "Gunta", "CSS Grid and Flexbox", "CSS Grid and Flexbox are modern CSS layout models that allow for creating flexible and responsive designs for websites and web applications. \n \nCSS Grid is a two-dimensional layout model that enables you to create rows and columns for arranging elements on a web page. You can define the size and behavior of these rows and columns and easily place elements within them. CSS Grid is particularly useful for creating complex and custom layouts that would otherwise be difficult to achieve with traditional CSS layout methods.\n \n Flexbox, on the other hand, is a one-dimensional layout model that allows you to control the alignment, direction, and order of elements within a container. With Flexbox, you can easily create flexible and responsive layouts that adapt to different screen sizes and device types. \n \nBoth CSS Grid and Flexbox offer numerous benefits over traditional CSS layout methods, including easier implementation of responsive and adaptive designs, improved alignment and spacing control, and more efficient use of screen real estate. Understanding these layout models is crucial for modern front-end development, and can greatly simplify the process of creating high-quality, user-friendly web designs.", "/css-image.jpg", "2022-05-01 11:30:22")
	stmt.Exec("2", "Emily", "Building a responsive website with CSS media queries", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/info-tech.jpg", "2022-09-01 10:30:22")
	stmt.Exec("3", "Emily", "Testing and debugging frontend code with Jest", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/app-testing.png", "2022-09-01 10:30:22")
	stmt.Exec("4", "Gunta", "The benefits of using CSS preprocessors such as SASS or LESS", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/website-layout.jpg", "2022-09-01 10:30:22")
	stmt.Exec("5", "Emily", "How to implement lazy loading for images and videos", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/css-image.jpg", "2022-09-01 10:30:22")
	stmt.Exec("6", "Rob", "Optimizing website performance with lazy loading, compression and minification", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/coding.jpg", "2022-09-01 10:30:22")
	stmt.Exec("7", "Emily", "Building interactive user interfaces with JavaScript and jQuery", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/css-image.jpg", "2022-09-01 10:30:22")
	stmt.Exec("8", "Gunta", "A comprehensive guide to React and its features", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/react-logo.jpg", "2022-09-01 10:30:22")
	stmt.Exec("9", "Rob", "State management in React using Redux and its alternatives", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/react-logo.jpg", "2022-09-01 10:30:22")
	stmt.Exec("10", "Rob", "Creating animations and transitions with CSS and JavaScript", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem nec neque egestas maximus a sit amet ante. Morbi vel ullamcorper erat. Sed congue, enim eu ultricies consectetur, diam eros aliquet urna, mollis elementum purus lectus non eros. Quisque a nulla sit amet mi consequat ultrices. Duis commodo erat at lacus auctor tristique. Vestibulum aliquam, mauris eu mollis rhoncus, nibh nulla convallis orci, eget iaculis risus nulla sit amet neque. Fusce porta ligula vitae posuere pellentesque.\n\n Curabitur at aliquam sapien. Cras rhoncus lorem enim, nec bibendum metus dignissim at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nec rutrum massa. Vivamus ac sapien a est commodo porta eget accumsan tortor. Cras sed pellentesque enim. Ut congue mattis sapien, eget rutrum sem dictum pulvinar. Mauris interdum auctor tellus ut rutrum. Nulla faucibus sit amet nisl vehicula scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum velit a lectus convallis fermentum. Donec at nisl orci. Nam mollis dui ac erat gravida, porttitor dapibus lorem ultricies. Nulla blandit molestie semper. Donec ac magna nibh. \n\n Fusce gravida feugiat tortor, nec commodo sem lacinia quis. Morbi orci velit, mollis eu pharetra a, volutpat sit amet elit. Nam consectetur lorem a hendrerit tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nulla dui, molestie eu augue vel, placerat porta tortor. In eu est ligula. Aenean vitae rhoncus augue. Fusce vestibulum nisi eu lacus cursus, quis aliquam tortor pellentesque. Quisque porttitor lacus eu mi gravida, ut gravida ante porttitor. Aenean finibus nisi at enim porttitor accumsan. Sed accumsan scelerisque est. Cras ac enim at ante porta euismod. Duis vitae maximus mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque a euismod nibh.", "/css-image.jpg", "2022-09-01 10:30:22")
}
