import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function PostPage({ postData }) {
  const router = useRouter()
  const postTitle = router.query.post

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {postData.map((post) => (
        <div className={styles.container} key={post.id}>
          <h1>{post.title}</h1> <br />
          <p style={{ color: 'grey' }}>Author: {post.username}</p>
          <br />
          <p>{post.content}</p>
        </div>
      ))}


    </>
  )
}

export async function getServerSideProps({ query }) {
  const postTitle = (query.slug).replaceAll("-", " ")
  console.log(postTitle);

  let data = {
    title: postTitle
  }

  const req = await fetch(`http://localhost:8080/post`, { method: "POST", body: JSON.stringify(data) });
  const incomingData = await req.json();
  // console.log(incomingData);
  return {
    props: { postData: incomingData },
  }
}